# Generated by Django 2.0.6 on 2018-06-25 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_person_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='document',
            field=models.FileField(blank=True, upload_to='documents/'),
        ),
    ]
